[package]
name = "aoz-sc-land-chest-opening-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.aoz-sc-land-chest-opening]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.7"
